version: 2.1
jobs:
  dockerize:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t devops .
      - run: docker tag devops tomflitterman/projet-devops:0.1.0
      - run: docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_USERNAME"
      - run: docker push tomflitterman/projet-devops:0.1.0
workflows:
  version: 2
  push_to_docker_hub:
    jobs:
      - dockerize