version: 2.1
jobs:
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: npm install
      - run:
          name: Run test
          command: npm run test
  dockerize:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t devops .
      - run:
          name: Tag image
          command: docker tag devops tomflitterman/projet-devops:$CIRCLE_TAG
      - run:
          name: Login to Docker Hub
          command: docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
      - run:
          name: Push image to Docker Hub
          command: docker push tomflitterman/projet-devops:$CIRCLE_TAG

workflows:
  test_and_push:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - dockerize:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - test