version: 2.1
jobs:
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  dockerize:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t devops .
      - run: docker tag devops tomflitterman/projet-devops:0.1.0
      - run: docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
      - run: docker push tomflitterman/projet-devops:0.1.0

workflows:
  test_and_push:
    jobs:
      - test
      - dockerize:
          requires:
            - test