version: 2.1
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: echo "A first hello"
  build2:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: echo "hello again"